--------------------------------------------------------------------------------
-- bias_hidden_rom.vhd
--
-- AUTO-GENERATED by phase3_vhdl_hardware/scripts/generate_vhdl_roms.py
-- from Phase 2's quantized parameters. DO NOT EDIT BY HAND --
-- re-run the generator script instead (after re-running Phase 2, if the
-- trained model or quantization format changed).
--
-- 16 entries, Q(QM, QN) fixed-point (see nn_pkg.vhd).
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.nn_pkg.all;

entity bias_hidden_rom is
    port (
        addr : in  integer range 0 to 16 - 1;
        data : out signed(DATA_WIDTH-1 downto 0)
    );
end entity bias_hidden_rom;

architecture rtl of bias_hidden_rom is
    type rom_array_t is array (0 to 16 - 1) of signed(DATA_WIDTH-1 downto 0);
    constant ROM_DATA : rom_array_t := (
        0 => to_signed(137, DATA_WIDTH),
        1 => to_signed(-5, DATA_WIDTH),
        2 => to_signed(171, DATA_WIDTH),
        3 => to_signed(-18, DATA_WIDTH),
        4 => to_signed(9, DATA_WIDTH),
        5 => to_signed(51, DATA_WIDTH),
        6 => to_signed(4, DATA_WIDTH),
        7 => to_signed(279, DATA_WIDTH),
        8 => to_signed(97, DATA_WIDTH),
        9 => to_signed(-28, DATA_WIDTH),
        10 => to_signed(17, DATA_WIDTH),
        11 => to_signed(-26, DATA_WIDTH),
        12 => to_signed(102, DATA_WIDTH),
        13 => to_signed(38, DATA_WIDTH),
        14 => to_signed(118, DATA_WIDTH),
        15 => to_signed(165, DATA_WIDTH)
    );
begin
    data <= ROM_DATA(addr);
end architecture rtl;
