--------------------------------------------------------------------------------
-- bias_output_rom.vhd
--
-- AUTO-GENERATED by phase3_vhdl_hardware/scripts/generate_vhdl_roms.py
-- from Phase 2's quantized parameters. DO NOT EDIT BY HAND --
-- re-run the generator script instead (after re-running Phase 2, if the
-- trained model or quantization format changed).
--
-- 10 entries, Q(QM, QN) fixed-point (see nn_pkg.vhd).
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.nn_pkg.all;

entity bias_output_rom is
    port (
        addr : in  integer range 0 to 10 - 1;
        data : out signed(DATA_WIDTH-1 downto 0)
    );
end entity bias_output_rom;

architecture rtl of bias_output_rom is
    type rom_array_t is array (0 to 10 - 1) of signed(DATA_WIDTH-1 downto 0);
    constant ROM_DATA : rom_array_t := (
        0 => to_signed(92, DATA_WIDTH),
        1 => to_signed(58, DATA_WIDTH),
        2 => to_signed(-151, DATA_WIDTH),
        3 => to_signed(-135, DATA_WIDTH),
        4 => to_signed(120, DATA_WIDTH),
        5 => to_signed(110, DATA_WIDTH),
        6 => to_signed(171, DATA_WIDTH),
        7 => to_signed(33, DATA_WIDTH),
        8 => to_signed(-259, DATA_WIDTH),
        9 => to_signed(-9, DATA_WIDTH)
    );
begin
    data <= ROM_DATA(addr);
end architecture rtl;
