"""
Generate synthesizable VHDL ROM entities from the quantized (fixed-point)
parameters produced in Phase 2.

Each ROM becomes a simple combinational lookup table: a VHDL constant array
indexed by an integer address (`data <= ROM_DATA(addr);`). This is the
standard, tool-independent way to turn trained-and-quantized weights into
hardware memory content, and synthesis tools (e.g. Vivado) will map it onto
LUTs or BRAM as appropriate.

Usage (with the venv activated, from inside phase3_vhdl_hardware/scripts/):
    python generate_vhdl_roms.py

Run this AFTER Phase 2's quantize_and_evaluate.py has produced the
*_dec.txt files in phase2_quantization/outputs/params_fixed/.
"""

import os

PHASE2_PARAMS_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..",
    "phase2_quantization", "outputs", "params_fixed"
)
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rtl", "roms")

# (source file from Phase 2, VHDL entity name to generate)
ROMS = [
    ("weights_hidden_dec.txt", "weights_hidden_rom"),
    ("bias_hidden_dec.txt", "bias_hidden_rom"),
    ("weights_output_dec.txt", "weights_output_rom"),
    ("bias_output_dec.txt", "bias_output_rom"),
]

ENTITY_TEMPLATE = """\
--------------------------------------------------------------------------------
-- {entity}.vhd
--
-- AUTO-GENERATED by phase3_vhdl_hardware/scripts/generate_vhdl_roms.py
-- from Phase 2's quantized parameters. DO NOT EDIT BY HAND --
-- re-run the generator script instead (after re-running Phase 2, if the
-- trained model or quantization format changed).
--
-- {count} entries, Q(QM, QN) fixed-point (see nn_pkg.vhd).
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.nn_pkg.all;

entity {entity} is
    port (
        addr : in  integer range 0 to {count} - 1;
        data : out signed(DATA_WIDTH-1 downto 0)
    );
end entity {entity};

architecture rtl of {entity} is
    type rom_array_t is array (0 to {count} - 1) of signed(DATA_WIDTH-1 downto 0);
    constant ROM_DATA : rom_array_t := (
{entries}
    );
begin
    data <= ROM_DATA(addr);
end architecture rtl;
"""


def generate_rom(source_file, entity_name):
    src_path = os.path.join(PHASE2_PARAMS_DIR, source_file)
    with open(src_path) as f:
        values = [int(line.strip()) for line in f if line.strip()]

    entry_lines = [
        f"        {i} => to_signed({v}, DATA_WIDTH)" for i, v in enumerate(values)
    ]
    entries = ",\n".join(entry_lines)

    vhdl_code = ENTITY_TEMPLATE.format(entity=entity_name, count=len(values), entries=entries)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"{entity_name}.vhd")
    with open(out_path, "w") as f:
        f.write(vhdl_code)
    print(f"Generated {out_path}  ({len(values)} entries)")


def main():
    for source_file, entity_name in ROMS:
        generate_rom(source_file, entity_name)
    print("\nAll ROMs generated. You can now compile the rtl/ directory with GHDL/Vivado/ModelSim.")


if __name__ == "__main__":
    main()
